server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
    cors:
      enabled: true
      allow_origins:
        - "*"
      allow_methods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
      allow_headers:
        - Content-Type
        - Authorization
        - X-Requested-With
        - X-CSRF-Token
      allow_credentials: true
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  mongo:
    uri: mongodb://localhost:27017
    database: quizzes
    password: root
    username: root
metadata:
  name: qwizler-quizzes
  env: dev
otel:
  trace:
    endpoint: localhost:4318
    insecure: true
  metrics:
    enable_exemplar: true
log:
  # zap | logrus
  logger: zap
  level: debug
  filepath: ""

